services:
  db-instance:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shawn
      POSTGRES_DB: e_commerce
    ports:
      - "5433:5432"

  e_commerce:
    container_name: main
    build: ./
    ports:
      - "8080:8080"
    environment:
      DB_URL: db:5432/e_commerce
      DB_USERNAME: postgres
      DB_PASSWORD: shawn
