spring:
  application:
    name: e-commerce

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL:localhost:5432/e_commerce}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:samarkand2004@@}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


springdoc:
  swagger-ui:
    path: /swagger

server:
  port: 8090

jwt:
  secret:
    key: 1wiehfpwif834qfbuhgwjKattaahilbfweufbpijwenqoirenvihHSHiprhfjn






